version: '3.8'

services:
  inj-trading-bot:
    build: .
    container_name: inj-trading-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Asia/Baku
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge
