version: '3.8'

services:
  gold-scalping-bot:
    build: .
    container_name: gold-scalping-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      - API_KEY=${API_KEY}
      - DATABASE_PATH=/app/data/trading_bot.db
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  bot-data:
  bot-logs:
